publish and add Travis CI
scholtzan/rdf-rs pull request #1
Opened 2018-03-23 17:29 UTC by MarcAntoine-Arnaud

2018-08-25 19:50 UTC, scholtzan requested changes
Thanks for fixing the formatting issues! :) 
Sorry for my (very) delayed review. I was quite busy the past few months but am planning to get back to that project (add SPARQL support, do some cleanup, ...).

I also saw that you published your fork on [crates.io](https://crates.io/crates/rdf). I think it might more sense to use the main repository there for publishing and add me as an owner there.

2018-08-25 19:50 UTC, scholtzan commented on Cargo.toml
> +repository = "https://github.com/media-io/rdf-rs"
I would prefer if this is the link to the main repo.

2018-08-27 08:21 UTC, MarcAntoine-Arnaud commented
Hi Anna !

Yes I'm agreed it can be better to add yourself too on the repository.
But right now I don't have your username on crates.io.

2018-08-27 08:22 UTC, MarcAntoine-Arnaud commented on Cargo.toml
> +repository = "https://github.com/media-io/rdf-rs"
Agreed if you are more active now it can be awesome !

2018-08-27 22:41 UTC, scholtzan commented
It should be the same as my Github user name: scholtzan

2018-08-28 06:07 UTC, MarcAntoine-Arnaud commented
I have invited you. I you can check.

2018-09-10 21:52 UTC, merged